FROM centos:7
LABEL maintainer "daikonretasu<daikonretasu1027@gmail.com>"

# CentOS ProjectのGPG公開鍵をインストールする
RUN rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

# インストール済みのパッケージをアップデート＆キャッシュのクリア
RUN yum -y update && yum clean all

#"Development and Creative Workstation"グループのインストール
RUN yum -y install deltarpm
RUN yum -y groupinstall "Development and Creative Workstation"

# 言語を日本語に設定
RUN localedef -i ja_JP -f UTF-8 ja_JP.UTF-8
RUN echo 'LANG="ja_JP.UTF-8"' >  /etc/locale.conf
ENV LANG ja_JP.UTF-8


# 日付を日本語に設定
RUN echo 'ZONE="Asia/Tokyo"' > /etc/sysconfig/clock
RUN rm -f /etc/localtime
RUN ln -fs /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

# manをインストールする前に、manファイルをインストールするように設定変更
RUN sed -i -e"s/^tsflags=nodocs/\# tsflags=nodocs/" /etc/yum.conf

# manと、man-pagesをインストール
RUN yum -y install man
RUN yum -y install man-pages.noarch
RUN yum -y install man-pages-ja.noarch

# xeyesのインストール
RUN yum -y install xeyes

#Eclipseダウンロード
RUN wget -q -O /tmp/eclipse-inst-linux64.tar.gz "http://ftp.jaist.ac.jp/pub/eclipse/technology/epp/downloads/release/2020-03/R/eclipse-jee-2020-03-R-incubation-linux-gtk-x86_64.tar.gz"
RUN tar zxvf /tmp/eclipse-* -C /opt/
RUN ln -s /opt/eclipse/eclipse /usr/bin

#フォント
RUN yum -y install ibus-kkc vlgothic-*

#Java
RUN wget -q -O /tmp/openjdk-11_linux-x64_bin.tar.gz  "https://download.java.net/java/ga/jdk11/openjdk-11_linux-x64_bin.tar.gz"
RUN tar zxf /tmp/openjdk-11_linux-x64_bin.tar.gz -C /usr/local
RUN alternatives --install /usr/bin/java java /usr/local/jdk-11/bin/java 2
RUN alternatives --install /usr/bin/jar jar /usr/local/jdk-11/bin/jar 2
RUN alternatives --install /usr/bin/javac javac /usr/local/jdk-11/bin/javac 2
RUN alternatives --set jar /usr/local/jdk-11/bin/jar
RUN alternatives --set javac /usr/local/jdk-11/bin/javac
RUN echo 3 | alternatives --config java

#maven
RUN wget -q  -O  /tmp/apache-maven-3.6.3-bin.tar.gz "https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz"
RUN tar zxf /tmp/apache-maven-3.6.3-bin.tar.gz -C /usr/local

#git
RUN yum -y install git


#環境変数
ENV JAVA_HOME /usr/local/jdk-11
ENV MAVEN_HOME /usr/local/apache-maven-3.6.3
ENV PATH $PATH:$JAVA_HOME/bin/:$MAVEN_HOME/bin/

#ワークスペースの作成からソース取得
#iDempiere
RUN mkdir /home/idempiere-workspace
RUN git clone https://github.com/JPiere/idempiere.git /home/idempiere-workspace/idempiere
RUN cd /home/idempiere-workspace/idempiere && git checkout -b release-7.1 origin/release-7.1
RUN cd /home/idempiere-workspace/idempiere/ && mvn validate
RUN cd /home/idempiere-workspace/idempiere/ && mvn verify
#Jpiere ピポッドと翻訳は除外
RUN mkdir /home/idempiere-workspace/jpiere
RUN git clone https://github.com/JPiere/JPCS.git /home/idempiere-workspace/jpiere/JPCS
RUN cd /home/idempiere-workspace/jpiere/JPCS && git checkout -b release-7.1 origin/release-7.1
RUN git clone https://github.com/JPiere/JPBP.git /home/idempiere-workspace/jpiere/JPBP
RUN cd /home/idempiere-workspace/jpiere/JPBP && git checkout -b release-7.1 origin/release-7.1
RUN git clone https://github.com/JPiere/JPFS.git /home/idempiere-workspace/jpiere/JPFS
RUN cd /home/idempiere-workspace/jpiere/JPFS && git checkout -b release-7.1 origin/release-7.1
RUN git clone https://github.com/JPiere/JPMS.git /home/idempiere-workspace/jpiere/JPMS
RUN cd /home/idempiere-workspace/jpiere/JPMS && git checkout -b release-7.1 origin/release-7.1
RUN git clone https://github.com/JPiere/jpiere.plugin.webui.formwindow.git /home/idempiere-workspace/jpiere/jpiere.plugin.webui.formwindow
RUN cd /home/idempiere-workspace/jpiere/jpiere.plugin.webui.formwindow && git checkout -b release-7.1 origin/release-7.1
RUN git clone https://github.com/JPiere/jpiere.plugin.webui.wysiwygeditor.git /home/idempiere-workspace/jpiere/jpiere.plugin.webui.wysiwygeditor
RUN cd /home/idempiere-workspace/jpiere/jpiere.plugin.webui.wysiwygeditor && git checkout -b release-7.1 origin/release-7.1
RUN git clone https://github.com/JPiere/jpiere.plugin.webui.simpleinputwindow.git /home/idempiere-workspace/jpiere/jpiere.plugin.webui.simpleinputwindow
RUN cd /home/idempiere-workspace/jpiere/jpiere.plugin.webui.simpleinputwindow && git checkout -b release-7.1 origin/release-7.1
RUN git clone https://github.com/JPiere/jpiere.plugin.webui.matrixwindow.git /home/idempiere-workspace/jpiere/jpiere.plugin.webui.matrixwindow
RUN cd /home/idempiere-workspace/jpiere/jpiere.plugin.webui.matrixwindow && git checkout -b release-7.1 origin/release-7.1
RUN git clone https://github.com/JPiere/jpiere.plugin.webui.dashboardgadget.git /home/idempiere-workspace/jpiere/jpiere.plugin.webui.dashboardgadget
RUN cd /home/idempiere-workspace/jpiere/jpiere.plugin.webui.dashboardgadget && git checkout -b release-7.1 origin/release-7.1
RUN git clone https://github.com/JPiere/jpiere.plugin.delete.git /home/idempiere-workspace/jpiere/jpiere.plugin.delete
RUN cd /home/idempiere-workspace/jpiere/jpiere.plugin.delete && git checkout -b release-7.1 origin/release-7.1
