FROM centos:7
LABEL maintainer "daikonretasu<daikonretas1027@gmail.com>"

# CentOS ProjectのGPG公開鍵をインストールする
RUN rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

# インストール済みのパッケージをアップデート＆キャッシュのクリア
RUN yum -y update && yum clean all

#"Development and Creative Workstation"グループのインストール
RUN yum -y install deltarpm
RUN yum -y groupinstall "Development and Creative Workstation"

# 言語を日本語に設定
RUN localedef -i ja_JP -f UTF-8 ja_JP.UTF-8
RUN echo 'LANG="ja_JP.UTF-8"' >  /etc/locale.conf
ENV LANG ja_JP.UTF-8


# 日付を日本語に設定
RUN echo 'ZONE="Asia/Tokyo"' > /etc/sysconfig/clock
RUN rm -f /etc/localtime
RUN ln -fs /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

# manをインストールする前に、manファイルをインストールするように設定変更
RUN sed -i -e"s/^tsflags=nodocs/\# tsflags=nodocs/" /etc/yum.conf

# manと、man-pagesをインストール
RUN yum -y install man
RUN yum -y install man-pages.noarch
RUN yum -y install man-pages-ja.noarch

#Eclipseダウンロード
RUN wget -q -O /tmp/eclipse-inst-linux64.tar.gz "http://ftp.jaist.ac.jp/pub/eclipse/technology/epp/downloads/release/2020-03/R/eclipse-jee-2020-03-R-incubation-linux-gtk-x86_64.tar.gz"
RUN tar zxvf /tmp/eclipse-* -C /opt/
RUN ln -s /opt/eclipse/eclipse /usr/bin

#フォント
RUN yum -y install ibus-kkc vlgothic-*

#Java
RUN wget -q -O /tmp/openjdk-11_linux-x64_bin.tar.gz  "https://download.java.net/java/ga/jdk11/openjdk-11_linux-x64_bin.tar.gz"
RUN tar zxf /tmp/openjdk-11_linux-x64_bin.tar.gz -C /usr/local
RUN alternatives --install /usr/bin/java java /usr/local/jdk-11/bin/java 2
RUN alternatives --install /usr/bin/jar jar /usr/local/jdk-11/bin/jar 2
RUN alternatives --install /usr/bin/javac javac /usr/local/jdk-11/bin/javac 2
RUN alternatives --set jar /usr/local/jdk-11/bin/jar
RUN alternatives --set javac /usr/local/jdk-11/bin/javac

#maven
RUN wget -q  -O  /tmp/apache-maven-3.6.3-bin.tar.gz "https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz"
RUN tar zxf /tmp/apache-maven-3.6.3-bin.tar.gz -C /usr/local

#git
RUN yum -y install git

#環境変数
RUN echo "JAVA_HOME=/usr/bin/java" >> /root/.bash_profile
RUN echo "MAVEN_HOME=/usr/local/apache-maven-3.6.3" >> /root/.bash_profile
RUN echo "PATH=$PATH:$JAVA_HOME/bin/:$MAVEN_HOME/bin/">> /root/.bash_profile
